refactor: util functions & split js code into modules
htmlacademy-javascript/1489831-keksobooking-22 pull request #4
Opened 2021-02-10 19:39 UTC by comm0nsense

2021-02-10 20:02 UTC, ArtMan-8 requested changes

2021-02-10 20:02 UTC, ArtMan-8 commented on js/data.js
> +const createOffer = () => {
Объект не правильной структуры
https://up.htmlacademy.ru/javascript/22/tasks/3

2021-02-10 20:02 UTC, ArtMan-8 commented on js/data.js
> +
А где экспорт? )

2021-02-10 20:02 UTC, ArtMan-8 commented on js/main.js
> +import './data.js';
А что импортируем?

2021-02-10 20:02 UTC, ArtMan-8 commented on js/util.js
> +  min = Math.ceil(+min);
Если на вход получаем целые числа, а по условию это так, то методы ceil и floor не обязательы

2021-02-10 20:04 UTC, ArtMan-8 requested changes

2021-02-10 20:04 UTC, ArtMan-8 commented on js/data.js
> +authors;
Это зачем?
И за комментированный код удалять не забываем.

2021-02-11 05:24 UTC, comm0nsense commented on js/data.js
> +
поправила

2021-02-11 05:24 UTC, comm0nsense commented on js/data.js
> +const OBJECTS_COUNT = 10;
поправила

2021-02-11 05:44 UTC, comm0nsense commented on js/util.js
> +  min = Math.ceil(+min);
убрала

2021-02-12 13:17 UTC, ArtMan-8 approved these changes

2021-02-12 13:17 UTC, ArtMan-8 commented on js/main.js
> +import {  offers } from './mock.js';
Лишний пробелы в скобках
У тебя встречаются и с пробелами, и без пробелов.
Выбери какой-то единый стиль, и придерживайся его.

2021-02-12 13:17 UTC, ArtMan-8 commented on js/mock.js
> +const getAuthor = () => {
В стрелочных функциях ретурн можно опускать

`const getAuthor = () => avatar: img/avatars/user0${getRandomInt(1, AVATAR_COUNT)}.png;`

2021-02-12 13:17 UTC, ArtMan-8 commented on js/mock.js
> +const getLocation = () => {
```
const getLocation = () => ({
    x: getRandomFloat(Coordinates.x.MIN, Coordinates.x.MAX, COORDINATE_DECIMALS_COUNT),
    y: getRandomFloat(Coordinates.y.MIN, Coordinates.y.MAX, COORDINATE_DECIMALS_COUNT),
})
```

2021-02-12 13:17 UTC, ArtMan-8 commented on js/mock.js
> +  let featureSet = [];
Не изменяемое значение

2021-02-12 13:17 UTC, ArtMan-8 commented on js/mock.js
> +  let location = getLocation()
Неизменяемое значение

2021-02-12 13:17 UTC, ArtMan-8 commented on js/mock.js
> +  let photoSet = [];
Неизменяемое значение

2021-02-12 13:17 UTC, ArtMan-8 commented on js/mock.js
> +  let shuffledFeatures = shuffleArray(FEATURES);
Неизменяемое значение

2021-02-12 13:17 UTC, merged